<?php

use App\Departement;
use Illuminate\Database\Seeder;

class DepartementsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Departement::truncate();
     /* Departement::create([
          'nom'=>'Aoujeft',
          'Region_id'=>'1'
      ]);
        Departement::create([
            'nom'=>'Atar',
            'Region_id'=>'1'
        ]);
        Departement::create([
            'nom'=>'Chinguity',
            'Region_id'=>'1'
        ]);
        Departement::create([
            'nom'=>'Ouadane',
            'Region_id'=>'1'
        ]);
        Departement::create([
            'nom'=>'Barkewol',
            'Region_id'=>'2'
        ]);
        Departement::create([
            'nom'=>'Guerou',
            'Region_id'=>'2'
        ]);
        Departement::create([
            'nom'=>'Boumdeid',
            'Region_id'=>'2'
        ]);
        Departement::create([
            'nom'=>'Kankossa',
            'Region_id'=>'2'
        ]);
        Departement::create([
            'nom'=>'Kiffa',
            'Region_id'=>'2'
        ]);
        Departement::create([
            'nom'=>'Aleg',
            'Region_id'=>'3'
        ]);
        Departement::create([
            'nom'=>'Boghe',
            'Region_id'=>'3'
        ]);
        Departement::create([
            'nom'=>'Bababe',
            'Region_id'=>'3'
        ]);
        Departement::create([
            'nom'=>'M\'Bagne',
            'Region_id'=>'3'
        ]);
        Departement::create([
            'nom'=>'Magta-lahjar',
            'Region_id'=>'4'
        ]);
        Departement::create([
            'nom'=>'Kaedi',
            'Region_id'=>'5'
        ]);
        Departement::create([
            'nom'=>'Mbout',
            'Region_id'=>'5'
        ]);
        Departement::create([
            'nom'=>'Monguel',
            'Region_id'=>'5'
        ]);
        Departement::create([
            'nom'=>'Maghama',
            'Region_id'=>'5'
        ]);
        Departement::create([
            'nom'=>'Ould Yenge',
            'Region_id'=>'6'
        ]);
        Departement::create([
            'nom'=>'Selibaby',
            'Region_id'=>'6'
        ]);
        Departement::create([
            'nom'=>'Amourdj',
            'Region_id'=>'7'
        ]);
        Departement::create([
            'nom'=>'Bassikounou',
            'Region_id'=>'7'
        ]);
        Departement::create([
            'nom'=>'Djigueni',
            'Region_id'=>'7'
        ]);
        Departement::create([
            'nom'=>'Nema',
            'Region_id'=>'7'
        ]);
        Departement::create([
            'nom'=>'oualata',
            'Region_id'=>'7'
        ]);
        Departement::create([
            'nom'=>'Timbedra',
            'Region_id'=>'7'
        ]);
        Departement::create([
            'nom'=>'Aiou El atrouss',
            'Region_id'=>'8'
        ]);
        Departement::create([
            'nom'=>'Kobenni',
            'Region_id'=>'8'
        ]);
        Departement::create([
            'nom'=>'Tamchkett',
            'Region_id'=>'8'
        ]);
        Departement::create([
            'nom'=>'Tintane',
            'Region_id'=>'8'
        ]);
        Departement::create([
            'nom'=>'Akjoujt',
            'Region_id'=>'9'
        ]);
        Departement::create([
            'nom'=>'Dar Naim',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'teyaret',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'Toujounine',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'Ksar',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'Sebkha',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'Tevrag Zeina',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'Araffat',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'El Mina',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'Riyadh',
            'Region_id'=>'10'
        ]);
        Departement::create([
            'nom'=>'Moudjeria',
            'Region_id'=>'11'
        ]);
        Departement::create([
            'nom'=>'Tichit',
            'Region_id'=>'11'
        ]);
        Departement::create([
            'nom'=>'Tidjigdja',
            'Region_id'=>'11'
        ]);
        Departement::create([
            'nom'=>'Bir Moghrein',
            'Region_id'=>'12'
        ]);
        Departement::create([
            'nom'=>'FDerick',
            'Region_id'=>'12'
        ]);
        Departement::create([
            'nom'=>'Zouerate',
            'Region_id'=>'12'
        ]);
        Departement::create([
            'nom'=>'Boutilimit',
            'Region_id'=>'13'
        ]);
        Departement::create([
            'nom'=>'Keurmacen',
            'Region_id'=>'13'
        ]);
        Departement::create([
            'nom'=>'Mededra',
            'Region_id'=>'13'
        ]);
        Departement::create([
            'nom'=>'Ouad Naga',
            'Region_id'=>'13'
        ]);
        Departement::create([
            'nom'=> 'RKis',
            'Region_id'=>'13'
        ]);
        Departement::create([
            'nom'=>'Rosso',
            'Region_id'=>'13'
        ]);
*/
    }
}
